### ISSUE TITLE
Available for use?

### ISSUE THREAD

**Issue by mamaral** [ricburton/trending#2]
Is this something that could be used in a production app? Looks like you're scraping the results, rather than use their search API?

**Comment by ricburton** [comment]
I used it for an iPhone app I built a couple of years ago. I couldn't get
the results from an official GitHub API at the time :)

**Comment by mamaral** [comment]
I'm assuming the API isn't really available for other people to use?

**Comment by ricburton** [comment]
I put the code up so someone could start up a Heroku instance and use it
themselves :)

Richard

**Comment by mamaral** [comment]
Gotcha, thanks!
